name: Build and deploy Vite app to Azure Web App - Machinery-system

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Disable CI checks
        run: echo "CI=false" >> $GITHUB_ENV
        
      - name: npm install
        run: |
          npm install
      - name: npm  build
        run: |
          npm run build --if-present
          

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0F3F59911BF74021B347FBD4B91691DE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A7BC6F1EE4274BEB9791D3A5380BF866 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E9761B6F8D4A47CD8F59E5322A8FFB63 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Machinery-system'
          slot-name: 'Production'
          package: ./build
          
