name: Build and deploy Vite app to Azure Web App - Machinery-system

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Add web.config to dist folder
        run: |
          cat <<EOF > dist/web.config
          <configuration>
            <system.webServer>
              <staticContent>
                <mimeMap fileExtension=".js" mimeType="application/javascript" />
                <mimeMap fileExtension=".css" mimeType="text/css" />
                <mimeMap fileExtension=".json" mimeType="application/json" />
                <mimeMap fileExtension=".wasm" mimeType="application/wasm" />
              </staticContent>
              <rewrite>
                <rules>
                  <rule name="SPA Vite Router" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/index.html" />
                  </rule>
                </rules>
              </rewrite>
            </system.webServer>
          </configuration>
          EOF

      - name: Zip artifact
        run: cd dist && zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0F3F59911BF74021B347FBD4B91691DE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A7BC6F1EE4274BEB9791D3A5380BF866 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E9761B6F8D4A47CD8F59E5322A8FFB63 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Machinery-system'
          slot-name: 'Production'
          package: .
          
